name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js and install dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Use the version you're working with

      - name: Install dependencies
        run: npm install

      # Run tests
      - name: Run tests
        run: npm test
