GET http://localhost:3001/api/users

###
GET http://localhost:3001/api/users/1

###
GET http://localhost:3001/api/users/total

###
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
    "username": "test",
    "email": "test",
    "password": "test"
}

###
PUT http://localhost:3001/api/users/username HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFwaWd1eTIzNCIsImlkIjoiMTEzIiwiaWF0IjoxNzI5MjQ0NzcwLCJleHAiOjE3MjkyNDgzNzB9.hFDlMxIFTO3yc1VeaKmxOzByGFQiwxW7QdapCC-v4jQ

{
    "username": "newusername"
}

###
DELETE http://localhost:3001/api/users/
