GET http://localhost:3001/api/users

###
GET http://localhost:3001/api/users/1

###
GET http://localhost:3001/api/users/total

###
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
    "username": "test",
    "email": "test",
    "password": "test"
}

###
PUT http://localhost:3001/api/users/username HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld3VzZXJuYW1lIiwiaWQiOiIxMTMiLCJpYXQiOjE3MjkzMjc4MDAsImV4cCI6MTcyOTMzMTQwMH0.CQfyfVuvA85iqvroC3pq7HH0OXLAmL3TpLqLhbVcAnM

{
    "username": "newusername"
}

###
PUT http://localhost:3001/api/users/email HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld3VzZXJuYW1lIiwiaWQiOiIxMTMiLCJpYXQiOjE3MjkzMjc4MDAsImV4cCI6MTcyOTMzMTQwMH0.CQfyfVuvA85iqvroC3pq7HH0OXLAmL3TpLqLhbVcAnM

{
    "email": "newmail@newmail.newmail"
}

###
DELETE http://localhost:3001/api/users/
