GET http://localhost:3001/api/users
x-auth-token: {{authToken}}

###
GET http://localhost:3001/api/users/3
x-auth-token: {{authToken}}

###
GET http://localhost:3001/api/users/total
x-auth-token: {{authToken}}

###
DELETE http://localhost:3001/api/users/
