name: Deployment pipeline

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install --production

      - name: Install Backend Dependencies
        run: |
          cd backend 
          npm install --production
          npm run build:ui

      - name: Deploy Backend Contents and Set Up on Server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            rsync --delete backend/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/html/
            supervisorctl status
